#!/usr/bin/env bash
# Installs Nginx with the following configurations:
## Nginx should be listening on port 80
## When querying Nginx at its root / with a GET request (requesting a page)\
### using curl, it must return a page that contains the string Hello World!

# Update the package list and install Nginx
apt-get update
apt-get -y install nginx

# Create the index.html file with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Configure Nginx to listen on port 80 and return "Hello World!" for requests to the root /
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Reload Nginx to apply the configuration
nginx -s reload
